// android/app/build.gradle.kts (in your main Flutter e-commerce app)

// Define the Flutter storage URL
val flutterStorageUrl: String = System.getenv("FLUTTER_STORAGE_BASE_URL") ?: "https://storage.googleapis.com"

repositories {
    // This maven block points to the local Maven repository generated by `flutter build aar`
    // Ensure the path is correct relative to your main app's directory
    maven {
        // IMPORTANT: Replace 'jodetx_payment_sdk' with the actual name of your Flutter module project folder
        // if it's different from 'jodetx_payment_sdk'.
        // This path is relative to the root of your Flutter module project.
        url = uri("/Users/jaipalreddy/Desktop/Rubel Shaikh/FlutterProjects/jodetx_payment_sdk/build/host/outputs/repo")
    }
    // This Maven repository is for Flutter's own artifacts
    maven {
        url = uri("$flutterStorageUrl/download.flutter.io")
    }
}

plugins {
    id("com.android.application")
    id("com.google.gms.google-services")
    id("kotlin-android") // Keep this if you have Kotlin code, even if MainActivity is Java
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.firebase.crashlytics")
}

android {
    namespace = "com.example.beauty_bag"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = "27.1.12297006"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        applicationId = "com.example.beauty_bag"
        minSdk = 24
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        multiDexEnabled = true
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
        }
        // Add the 'profile' build type if it's not already present
        getByName("profile") { // Use getByName to access the existing 'profile' build type
            initWith(getByName("debug")) // Inherit from debug
            // You can add other profile-specific configurations here if needed
        }
    }
}

dependencies {
    debugImplementation("com.example.jodetx_payment_sdk:flutter_debug:1.0")
    profileImplementation("com.example.jodetx_payment_sdk:flutter_profile:1.0")
    releaseImplementation("com.example.jodetx_payment_sdk:flutter_release:1.0")
}

flutter {
    source = "../.."
}
